# Generated by Django 2.0.4 on 2018-04-30 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='message file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='spicker.Group', verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='message image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='message text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='spicker.Group', verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='avatar')),
                ('contacts', models.ManyToManyField(related_name='_profile_contacts_+', related_query_name='contact', to='spicker.Profile', verbose_name='contacts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('finished', models.DateTimeField(blank=True, default=None, verbose_name='finished')),
                ('duration', models.DurationField(blank=True, default=None, verbose_name='duration')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_call', to='spicker.Group', verbose_name='group')),
            ],
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spicker.Message', verbose_name='message'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='spicker.Profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spicker.Profile', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='spicker.GroupMember', to='spicker.Profile', verbose_name='members'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spicker.Message', verbose_name='message'),
        ),
    ]
